import { formatSize } from "@earendil-works/pi-coding-agent";

export const CODE_INTEL_CACHE_VERSION = 6;
export const DEFAULT_MAP_TOKENS = 1600;
export const DEFAULT_MAX_FILES = 2500;
export const DEFAULT_MAX_FILE_BYTES = 512 * 1024;
export const MAX_SIGNATURE_LINES = 12;
export const IDENT_RE = /\b[A-Za-z_][A-Za-z0-9_]{2,}\b/g;

export const CODE_INTEL_SCHEMA = {
	type: "object",
	properties: {
		action: {
			type: "string",
			enum: [
				"repo_map",
				"status",
				"outline",
				"symbols",
				"slice",
				"enclosing_symbol",
				"definition",
				"references",
				"hover",
			],
			description:
				"Operation to run. Orient with repo_map, locate with symbols, inspect bodies with slice, find usages with LSP-backed references, convert usage locations to caller context with enclosing_symbol, then slice callers. Use outline for structure; definition/references/hover require LSP; status reports backend availability.",
		},
		root: {
			type: "string",
			description: "Optional project root. Defaults to current working directory or git root.",
		},
		mapTokens: {
			type: "number",
			description: `Approximate token budget for repo_map output. Default ${DEFAULT_MAP_TOKENS}.`,
		},
		maxFiles: { type: "number", description: `Maximum source files to scan. Default ${DEFAULT_MAX_FILES}.` },
		maxFileBytes: {
			type: "number",
			description: `Maximum bytes per file to scan. Default ${formatSize(DEFAULT_MAX_FILE_BYTES)}.`,
		},
		include: { type: "array", items: { type: "string" }, description: "Optional substrings paths must include." },
		exclude: {
			type: "array",
			items: { type: "string" },
			description: "Optional substrings paths must not include.",
		},
		query: {
			type: "string",
			description:
				"Identifier/file hint for repo_map, or locator query for symbols; follow symbol matches with slice.",
		},
		path: {
			type: "string",
			description:
				"File path for outline, slice, enclosing_symbol, definition, references, or hover. Pass a reference location to enclosing_symbol to identify its caller.",
		},
		symbol: {
			type: "string",
			description:
				"Symbol name. Prefer slice for its body and LSP-backed references for usages; symbols only locates candidates.",
		},
		line: {
			type: "number",
			description:
				"1-based line for enclosing_symbol or LSP lookup. Use enclosing_symbol on a reference line, then slice the returned caller.",
		},
		column: { type: "number", description: "1-based column number for LSP-backed position lookups." },
		limit: {
			type: "number",
			description:
				"Maximum locator results for symbols. Default 50; use slice rather than reading matched files broadly.",
		},
		sliceMode: {
			type: "string",
			enum: ["implementation", "declaration", "any"],
			description: 'Preferred body for slice: implementation, declaration, or any. Default "any".',
		},
	},
	required: ["action"],
	additionalProperties: false,
};

export const EXT_TO_LANGUAGE = new Map<string, string>([
	[".ts", "typescript"],
	[".tsx", "tsx"],
	[".js", "javascript"],
	[".jsx", "jsx"],
	[".mjs", "javascript"],
	[".cjs", "javascript"],
	[".go", "go"],
	[".py", "python"],
	[".rs", "rust"],
	[".tf", "terraform"],
	[".tfvars", "terraform"],
	[".tfcomponent.hcl", "terraform"],
	[".tfstack.hcl", "terraform"],
	[".tfdeploy.hcl", "terraform"],
	[".tfquery.hcl", "terraform"],
	[".java", "java"],
	[".kt", "kotlin"],
	[".kts", "kotlin"],
	[".rb", "ruby"],
	[".php", "php"],
	[".cs", "csharp"],
	[".c", "c"],
	[".h", "c"],
	[".cc", "cpp"],
	[".cpp", "cpp"],
	[".cxx", "cpp"],
	[".hpp", "cpp"],
	[".swift", "swift"],
	[".scala", "scala"],
	[".ex", "elixir"],
	[".exs", "elixir"],
	[".erl", "erlang"],
	[".hrl", "erlang"],
]);

export const LANGUAGE_SPECIFIC_PATTERN_SUPPORT = new Set([
	"typescript",
	"tsx",
	"javascript",
	"jsx",
	"go",
	"python",
	"rust",
	"terraform",
	"java",
	"kotlin",
	"csharp",
	"php",
	"ruby",
	"c",
	"cpp",
	"swift",
]);

export const SKIP_DIRS = new Set([
	".git",
	"node_modules",
	"dist",
	"build",
	"target",
	"vendor",
	"coverage",
	".next",
	".nuxt",
	".turbo",
	".cache",
	"tmp",
	"temp",
]);

export const KEYWORDS = new Set([
	"abstract",
	"and",
	"as",
	"async",
	"await",
	"break",
	"case",
	"catch",
	"class",
	"const",
	"continue",
	"def",
	"default",
	"defer",
	"do",
	"else",
	"enum",
	"export",
	"extends",
	"false",
	"final",
	"finally",
	"fn",
	"for",
	"from",
	"func",
	"function",
	"if",
	"impl",
	"import",
	"in",
	"interface",
	"let",
	"match",
	"mod",
	"module",
	"namespace",
	"new",
	"nil",
	"none",
	"not",
	"null",
	"or",
	"package",
	"private",
	"protected",
	"pub",
	"public",
	"return",
	"self",
	"static",
	"struct",
	"super",
	"switch",
	"this",
	"trait",
	"true",
	"try",
	"type",
	"undefined",
	"use",
	"var",
	"void",
	"while",
]);
